version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: transactionsdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  transactions-api:
    build: .
    container_name: transactions-api
    ports:
      - "8005:8005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transactionsdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db-data:
